### PR TITLE
fix: `/superplay next` with an empty queue throws ParrotError::NotInRange

### LINKED ISSUE #207: `/superplay next` with an empty queue throws ParrotError::NotInRange
### 📝 Description

The `insert_track` function should account for the queue possibly being empty. Right now, it's responding with a confusing (and incorrect) error. In that case, it should just insert the track on the first position.

### 🪜 Reproduction Steps

1. Ensure the queue is empty.
2. Call **/superplay next query: asdf**.
3. Parrot should reply with "_index should be between 1 and 0 but was 1_", which is incorrect. Instead, it should just insert the track to the first position.

### ℹ Environment / Computer Info

- **Parrot version**: `v1.4.2`
- **Operating System**: Windows 11

### 📸 Screenshots

image

### PR DESCRIPTION
**Pull request by aquelemiguel**
Resolves #207. Also removed the NotInRange check altogether as there's no real way it can fail.

### CODE REVIEW

File: src/commands/play.rs [hunk 1]
```diff
@@ -365,10 +365,10 @@ async fn insert_track(
     let queue_size = handler.queue().len();
     drop(handler);
 
-    verify(
-        idx != 0 && idx < queue_size,
-        ParrotError::NotInRange("index", idx as isize, 1, queue_size as isize),
-    )?;
```
Comment (joao-conde) [inline src/commands/play.rs:371]: Yeah but insert 5 on a queue of length 3 now is not checked right?

Comment (aquelemiguel) [reply src/commands/play.rs:371]: Correct, but looking at these function calls I can't really see how that scenario is possible. Am I overlooking something?

Comment (joao-conde) [reply src/commands/play.rs:371]: If insert is called with our index command?

Comment (aquelemiguel) [reply src/commands/play.rs:371]: You mean a command for inserting a track in a specific position in the queue? We don't have that.

Comment (aquelemiguel) [reply src/commands/play.rs]: Added the assertion back. Idx is always >=1, so having the assert before the new code would fail (1 <= 0). So I added it as a safeguard for the already existing one.

**Review by joao-conde — APPROVED** [review]

**Review by afonsojramos — APPROVED** [review]
