### PR TITLE
fix: `queue` & `np` check

### LINKED ISSUE #129: `np` & `queue` error messages
## Description
Some errors introduced in #122 (image 1) were partially fixed in #125, however, this also introduced a bug (image 2).

## Observed behaviour
1. Image 1 - Bot is not connected
image

2. Image 2 - User is not connected
image

## Expected behaviour
1. Bot is not connected -> `FAIL_NO_VOICE_CONNECTION` error
image
2. User is not connected -> Normal behaviour
image

### PR DESCRIPTION
**Pull request by afonsojramos**
Closes #129.

### CODE REVIEW

File: src/handlers/serenity.rs [hunk 1]
```diff
@@ -299,7 +299,7 @@ impl SerenityHandler {
                     _ => Ok(()),
                 }
             }
-            "queue" | "np" => match check_voice_connections(&guild, &user_id, &bot_id) {
+            "np" | "queue" => match check_voice_connections(&guild, &user_id, &bot_id) {
```
Comment (aquelemiguel) [inline src/handlers/serenity.rs:302]: 👏👏👏👏👏

**Review by aquelemiguel — APPROVED** [review]

**Review by aquelemiguel — APPROVED** [review]
